### PR TITLE
Amazon- and ADE-compatible hr text dividers

### PR DESCRIPTION
**Pull request by arthurattwell**
@SteveBarnett Testing on Webkit-based ereaders, Amazon Kindle and Adobe Digital Editions turned up some frustrating inconsistencies in how they support CSS for the `hr` element, which we use for  conventional dividers in running text.

In print and web, we use `content:` and `border: 0` to use `hr` as a text divider. Sometimes, we use `background-image` for a decorative text divider. On Kindle, if we set `border: 0` though (or use any other way to remove the border), the `hr` collapses entirely, leaving no text divider space at all.

So, for epub, our only option (after several hours testing options) seems to be to use `background-image` to achieve consistently in epubs what we get with `content:` in web and print.

As for that background-image, I don't think we should ship an image file in the template (e.g. a user might delete it by mistake or not understand why it's there). So I've embedded a bullet character as a data-uri, and assigned it to a default Sass variable `$text-divider-image` so it can be easily replaced from a book's `epub.scss`.

### CODE REVIEW

**Comment by SteveBarnett** [comment]
Given that a `transparent` border also doesn't work (as discussed IRL), using a background image seems like an okay solution.

I feel funny about using a base64 encoded image: they're big for what they are. I'm worried that we'll start using a bunch of them, bump the CSS file size up, and lose the benefits of the image(s) being cached.

So: an awkard 👍  :)

**Comment by arthurattwell** [comment]
@SteveBarnett How about, instead of a bullet, our default background-image is a transparent gif:

```
$text-divider-image: data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7 !default;

hr {
   background-image: url($text-divider-image);
   border: 0;
}
```

(Found that [here](https://css-tricks.com/almanac/properties/b/background-image/#article-header-id-0).)

That is, our default text divider is actually just space, and it's a really tiny data-uri. Then if you want an actual image, you specify it in sass config with `$text-divider-image` and add the image yourself.

That way, we avoid a long data-uri and keep to our general principle of providing a minimally opinionated default design.

I haven't tested this yet.

**Comment by arthurattwell** [comment]
@SteveBarnett New information! TL;DR: we can't use a data-uri after all. So to use `background-image` we may have to put an image in the template after all.

This emerged today when eagle-eyes Wesley Thompson (checking Pan Mac epubs) unearthed a bug that was driving me crazy that seemed unrelated.

When converting our epubs to mobi in KindleGen, conversion crashes when I add the metadata `<meta content="cover.jpg" name="cover" />` to `content.opf`. This metadata tag is completely valid and standard, and is what many ereaders use to identify the image file for use in gallery/bookshelf views.

If I used a different `name`, e.g. `<meta content="cover.jpg" name="cover-image" />`, KindleGen did not crash. But a different name would not help those ereaders, which need `name="cover"`.

Turns out, if I remove the `data:image` from the CSS, no crash! Inexplicably, KindleGen crashes in the presence of both a data-uri image _and_ `<meta content="cover.jpg" name="cover" />`.

**Comment by SteveBarnett** [comment]
@arthurattwell Er, yay, I guess? ;)
Tiny background image placeholder thingy it is.

**Comment by arthurattwell** [comment]
@SteveBarnett Thought you might like that ;) However, I'm finding further hassle with a linked background-image. When opening the files in Sigil – unlike images linked in HTML files – Sigil does not import background image files linked in CSS, nor does it update its paths to those images. This means that, in order to create a valid epub with a CSS background image, you have to manually add the image file and update the path in the CSS. PITA.

So I'm in search of a new solution to the original problem: `hr`s that collapse in Kindle when they have neither a border nor a background image.

**Comment by arthurattwell** [comment]
@SteveBarnett Okay, I'm fried. I have tried *everything* to work around Kindle's weirdness,* and in the end have gone with something very simple. Essentially, if Kindle's CSS support is broken I'm not going to try to work around that if it breaks output everywhere else. In Kindle, you'll just see a horizontal rule.

Anyway, how's this look now?

\* On Kindle weirdness. Just noting this here for posterity. Normally, as noted earlier, Kindle collapses  the space when a border on an `hr` is made non-visible in any way. One thing I tried was to add `:after` content, which did not work, *unless* I add more than about twenty characters using `:after` content (e.g. to a heading elswhere in the document): then the `hr`s behave as expected, leaving space perfectly! *But* font support in the document breaks completely: no more distinction between serif and sans-serif. I'm guessing that a certain amount of CSS content generation triggers some kind of non-default conversion process or rendering engine.

**Comment by SteveBarnett** [comment]
👍 for least-bad solution that also is okay on Kindles :D

**Comment by arthurattwell** [comment]
@SteveBarnett Don't know why I didn't think of this before, but this seems to work in Kindle:

```
hr {
    border: 0;
    &:after {
        content: normal;
    }
    // workaround to add space after hr in Kindle
    & + * {
        margin-top: 1em;
    }
}

```

which is to add the space we need above the element after the `hr`, rather than trying to add it to the `hr`. I don't want to bake it into the template (yet), but want to test this in the wild some more first.

**Comment by arthurattwell** [comment]
I've also recently tried 2641d3869cbaee2e3a374218e9b94e60f3fb1303, but still testing in the wild. This uses `hr { margin-left: -200% }` in a Kindle-targeted media query to move the HR out of view, but retain the space.

**Pull request merged**
