### PR TITLE
Remove darken on hover, only use box-shadow on hover

### PR DESCRIPTION
**Pull request by arthurattwell**
Minor tweak to default button styling. Should take you about five seconds to glance through, @SteveBarnett?

No idea why the diff is showing indentation changes.

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@arthurattwell Code looks fine (of course :) ), but honestly I'm not sure about this change.

I think that the existing version has a visually clearer difference between regular and hovered states. In fact, I'd rather keep the existing one but make the change in colour even greater: use 20% instead of 5% everywhere.

We could also add our own `focus` styles, but maybe that's for a separate PR.

**Comment by arthurattwell** [comment]
@SteveBarnett Thanks, yeah. So maybe there's a better route to my aim here, which is to use as little CSS as possible in the template, to make custom-CSS overrides much easier, especially for user with less CSS experience. Ideally, our hover state would only use one line of well-known CSS. Any other ideas?

**Comment by SteveBarnett** [comment]
1. Darken (or lighter) background on hover as above. We could do this using the Sass function as we where, or have a new variable `$color-buttons-hover` which is `darken( $color-buttons, 20% )`by default. (and can be set to a different, manual, colour). That would allow peeps to use Sass if they know it, or just use a hex / rgb if they don't. 

I think this is the preferred option because it's the most common pattern on the interwebs (bg colour changes on hover), so people will be used to it.

2. Borders. We could have transparent borders by default and change border colours on hover. This will also give the user a visually clear change.

**Comment by arthurattwell** [comment]
@SteveBarnett Ah, perfectly simple, thanks. Done. How's that look?

**Comment by SteveBarnett** [comment]
@arthurattwell Bueno! 👍

**Pull request merged**
