### PR TITLE
Gulped images

### PR DESCRIPTION
**Pull request by SteveBarnett**
@arthurattwell what do you think of this?

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@arthurattwell Ping!

I feel like we discussed something extra here, but I don't remember what. Do you? 😊

**Comment by arthurattwell** [comment]
@SteveBarnett It may have been that we weren't sure whether to ship this with the template? I think the template should work without gulp, and adding and using it would be For Advanced Users.

**Comment by SteveBarnett** [comment]
@arthurattwell Ah yes, of course. How do you want to go forward?

1. Close this PR and think about this later.
2. Add a note something like "If you're familiar with the command line and gulp, then..."
3. Something else?

**Comment by arthurattwell** [comment]
@SteveBarnett I'm happy to leave the PR open, or at least leave the branch active, but first see how we use or develop this with CORE and maybe another project or two before we put it in the template. How's that sound?

**Comment by SteveBarnett** [comment]
@arthurattwell Groovy. Let's close the PR for now to get it off the radar a bit. We can always re-open it later. :)

**Pull request closed without merging**
