### PR TITLE
JS-powered navigation part 2

### PR DESCRIPTION
**Pull request by SteveBarnett**
Carrying on from #33 . :)

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@arthurattwell Moving this convo to new PR after 👻 -merge of previous one. How's this looking now? :)

**Comment by arthurattwell** [comment]
@SteveBarnett I've tweaked added some things, all tested pretty thoroughly with the Lawful Living project. How's it look to you?

**Comment by SteveBarnett** [comment]
@arthurattwell Updates look great to me (even the spaces ;) ), but I would like to argue against using `position: fixed` (see #055d6ba395bcef30a22fb98ac35b96015cd287ef). 

1. Although [support is sort of good](http://caniuse.com/#search=position%3Afixed), support is sort of bad: implementation tends to be buggy and janky on lower-powered / small screen devices.

2. I don't think it looks nice 😬. It obscures part of the text ([screencap](https://cloud.githubusercontent.com/assets/1239497/20923093/86fa04be-bbb3-11e6-857c-262de88f5845.jpg) "Contents theme make them look lovely"), which can especially be a problem on smaller screens. I came for the content, not the nav.

**Comment by arthurattwell** [comment]
@SteveBarnett Great point, which also led me to [this useful overview](http://bradfrost.com/blog/mobile/fixed-position/). So (a) there are going to be clients who insist, and (b) this is most likely to happen in books with long chapters where nav is really central to the experience, and scrolling to the top to get at the nav is a pain (e.g. Lawful Living). So would it be pragmatic to go for one or both of these compromises:

1. Add some CSS precedence that (maybe sometimes?) falls back to `position: absolute` on browsers that don't support `fixed` at all
2. Set the template default Sass, with a note, as `$nav-bar-fixed: false !default; // fixed is not fully supported on many mobile browsers`
3. Put user agent sniffing on our roadmap to add a device-aware solution later.

Oh you're going to love the fixed 'Go to top' button option I'm about to PR ;) [ducks]

**Comment by SteveBarnett** [comment]
@arthurattwell Hmm. Here are my further thoughts.

1. Will require some ([admittedly small](https://github.com/filamentgroup/fixed-fixed)) JavaScript for best testing and results so if we can avoid it we should.
2. Seems like the best choice to me. I kind of want to have a line in there about "it's bad UX because it obscures the content" too, but I think that will rather go in a chat with the client. So I'm in for this option.
3. Makes me [skyward scream](http://tvtropes.org/pmwiki/pmwiki.php/Main/SkywardScream). I am generally against user agent sniffing as it's not very [Future Friendly](http://futurefriendly.co.za/) (my site, sorry! 😬 ). Feature-testing is generally better.

Re "Go to top": I will have comments to make there! :D (But, TL;DR: general feeling is that users have the scrollbar / their thumb, so they don't need those links. Except on extremely long pages (but then the problem is that the page shouldn't be so long ¯\\\_(ツ)_/¯ ))

**Comment by arthurattwell** [comment]
@SteveBarnett Cool, thanks, have gone with not-fixed by default. PR good to go?

**Comment by SteveBarnett** [comment]
@arthurattwell Cool, good to go 👍. I think, because of the weird 👻 -merge, we should get this in to develop and have a final eyeball at The Two PRs when they're mushed together.

**Comment by arthurattwell** [comment]
@SteveBarnett FYI I've put my 'go to top' button in issue #44 for future reference, rather than a PR for the default template.

**Pull request merged**
